theme: jekyll-theme-cayman
title: "Antibiotic Resistance Analysis"
description: "My first hands-on exploration of antibiotic resistance data and basic machine learning concepts."
author: "Luca Scarpantonio"
url: "https://lucascarpantonio.github.io/antibiotic_resistance/blog"
